## Get Started with Delta Lake using Databricks | Benefits and Features of Delta Lake | Time Travel

In [2]:
from databricks.connect import DatabricksSession
# Build the Databricks Connect session
spark = DatabricksSession.builder.getOrCreate()

In [2]:
spark

In [ ]:
# Default catalog implementation for Databricks, if its unity catalog or hive metastore?
# spark.conf.get("spark.sql.catalogImplementation", "not-set")
print(spark.catalog.currentCatalog());
# display(spark.sql("SELECT current_catalog() AS catalog, current_schema() AS schema"))

workspace

In [18]:
display(spark.sql("SHOW CATALOGS"))

DataFrame[catalog: string]

In [21]:
spark.sql("SHOW DATABASES").show()

+------------------+
|      databaseName|
+------------------+
|           default|
|information_schema|
+------------------+

In [22]:
# Read Sale parquet data
df_sales = spark.read.parquet("/Volumes/workspace/default/data/input/sales_data.parquet")

In [23]:
# View data
df_sales.show()

+-------------------+----------+-----------+--------------------+-------+----------+
|      transacted_at|    trx_id|retailer_id|         description| amount|   city_id|
+-------------------+----------+-----------+--------------------+-------+----------+
|2017-11-24 19:00:00|1995601912| 2077350195|Walgreen       11-25| 197.23| 216510442|
|2017-11-24 19:00:00|1734117021|  644879053|unkn    ppd id: 7...|   8.58| 930259917|
|2017-11-24 19:00:00|1734117022|  847200066|Wal-Mart  ppd id:...|1737.26|1646415505|
|2017-11-24 19:00:00|1734117030| 1953761884|Home Depot     pp...|  384.5| 287177635|
|2017-11-24 19:00:00|1734117089| 1898522855| Target        11-25|  66.33|1855530529|
|2017-11-24 19:00:00|1734117117|  997626433|Sears  ppd id: 85...| 298.87| 957346984|
|2017-11-24 19:00:00|1734117123| 1953761884|unkn   ppd id: 15...|  19.55|  45522086|
|2017-11-24 19:00:00|1734117152| 1429095612|Ikea     arc id: ...|   9.39|1268541279|
|2017-11-24 19:00:00|1734117153|  847200066|unkn        Kings...|2907.57|1483931123|
|2017-11-24 19:00:00|1734117212| 1996661856|unkn    ppd id: 4...| 140.38| 336763936|
|2017-11-24 19:00:00|1734117241|  486576507|              iTunes|2912.67|1663872965|
|2017-11-24 19:00:00|2076947148|  847200066|Wal-Mart         ...|  62.83|1556600840|
|2017-11-24 19:00:00|2076947147|  562903918|McDonald's    ccd...|  31.37| 930259917|
|2017-11-24 19:00:00|2076947146|  511877722|unkn     ccd id: ...|1915.35|1698762556|
|2017-11-24 19:00:00|2076947113| 1996661856|AutoZone  arc id:...| 1523.6|1759612211|
|2017-11-24 19:00:00|2076947018|  902350112|DineEquity    arc...|  22.28|2130657559|
|2017-11-24 19:00:00|2076946994| 1898522855|Target    ppd id:...|2589.93|2074005445|
|2017-11-24 19:00:00|2076946985|  847200066|Wal-Mart    ppd i...|   42.2| 459344513|
|2017-11-24 19:00:00|2076946960|  386167994|Wendy's  ppd id: ...|  14.62| 352952442|
|2017-11-24 19:00:00|2076946954|  486576507|iTunes     ppd id...|  37.42| 485114748|
+-------------------+----------+-----------+--------------------+-------+----------+
only showing top 20 rows

In [25]:
display(df_sales)

DataFrame[transacted_at: timestamp, trx_id: int, retailer_id: int, description: string, amount: double, city_id: int]

In [24]:
display(df_sales.toPandas())

,transacted_at,trx_id,retailer_id,description,amount,city_id
0,2017-11-24 19:00:00,1995601912,2077350195,Walgreen 11-25,197.23,2.165104e+08
1,2017-11-24 19:00:00,1734117021,644879053,unkn ppd id: 768641 11-26,8.58,9.302599e+08
2,2017-11-24 19:00:00,1734117022,847200066,Wal-Mart ppd id: 555914 Algiers 11-26,1737.26,1.646416e+09
3,2017-11-24 19:00:00,1734117030,1953761884,Home Depot ppd id: 265293 11-25,384.50,2.871776e+08
4,2017-11-24 19:00:00,1734117089,1898522855,Target 11-25,66.33,1.855531e+09
...,...,...,...,...,...,...
1102571,2017-05-08 17:00:00,1750167174,202319369,unkn,208.51,1.773944e+09
1102572,2017-05-08 17:00:00,1750166461,1070485878,Amazon.com ppd id: 620086 Columbia,4.78,4.818216e+08
1102573,2017-05-08 17:00:00,1750166460,2139149619,"unkn ppd id: 735650 Vaiaku village, Funa...",18.51,6.993004e+08
1102574,2017-05-08 17:00:00,1750166457,887300947,Kroger arc id: 997483,2755.33,1.802489e+09
1102575,2017-05-08 17:00:00,1750166455,847200066,unkn ccd id: 590430 Providence,41.60,NaN

In [ ]:
# Write data as managed table
df_sales.write.format("parquet").mode("overwrite").option("path","/Volumes/workspace/default/data/output/sales_parquet/").save()
df_sales.write.mode("overwrite").saveAsTable("workspace.default.sales_parquet")

In [34]:
# View files
dbutils.fs.ls("/Volumes/workspace/default/data/output/sales_parquet/")

[FileInfo(path='/Volumes/workspace/default/data/output/sales_parquet/_SUCCESS', name='_SUCCESS', size=0, modificationTime=1789593929000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_parquet/_committed_498013408330543316', name='_committed_498013408330543316', size=123, modificationTime=1789593928000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_parquet/_started_498013408330543316', name='_started_498013408330543316', size=0, modificationTime=1789593927000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_parquet/part-00000-tid-498013408330543316-056f8376-b6fd-4e93-9cd2-4c06d60f6533-133-1.c000.snappy.parquet', name='part-00000-tid-498013408330543316-056f8376-b6fd-4e93-9cd2-4c06d60f6533-133-1.c000.snappy.parquet', size=27297385, modificationTime=1789593928000)]

In [ ]:
# Another way to view files using the Databricks SDK
from databricks.sdk import WorkspaceClient
# Initializes client using your DATABRICKS_HOST and DATABRICKS_TOKEN environment variables
w = WorkspaceClient()
# Counterpart to dbutils.fs.ls("/Volumes/workspace/default/data/output/")
files = w.files.list_directory_contents(directory_path="/Volumes/workspace/default/data/output/sales_parquet/")
for f in files:
	print(f"Path: {f.path}, Name: {f.name}, Size: {f.file_size} bytes, Last Modified: {f.last_modified}")

Path: /Volumes/workspace/default/data/output/sales_parquet/_SUCCESS, Name: _SUCCESS, Size: 0 bytes, Last Modified: 1789593929000
Path: /Volumes/workspace/default/data/output/sales_parquet/_committed_498013408330543316, Name: _committed_498013408330543316, Size: 123 bytes, Last Modified: 1789593928000
Path: /Volumes/workspace/default/data/output/sales_parquet/_started_498013408330543316, Name: _started_498013408330543316, Size: 0 bytes, Last Modified: 1789593927000
Path: /Volumes/workspace/default/data/output/sales_parquet/part-00000-tid-498013408330543316-056f8376-b6fd-4e93-9cd2-4c06d60f6533-133-1.c000.snappy.parquet, Name: part-00000-tid-498013408330543316-056f8376-b6fd-4e93-9cd2-4c06d60f6533-133-1.c000.snappy.parquet, Size: 27297385 bytes, Last Modified: 1789593928000

In [35]:
# spark.sql("SHOW TABLES IN default").show()
display(spark.sql("SHOW TABLES IN default"))

DataFrame[database: string, tableName: string, isTemporary: boolean]

In [ ]:
# spark.sql('DESCRIBE EXTENDED sales_parquet').show()
display(spark.sql('DESCRIBE EXTENDED sales_parquet'))

DataFrame[col_name: string, data_type: string, comment: string]

In [39]:
spark.sql("SELECT * FROM workspace.default.sales_parquet where trx_id = '1995601912'").show()

+-------------------+----------+-----------+--------------------+------+---------+
|      transacted_at|    trx_id|retailer_id|         description|amount|  city_id|
+-------------------+----------+-----------+--------------------+------+---------+
|2017-11-24 19:00:00|1995601912| 2077350195|Walgreen       11-25|197.23|216510442|
+-------------------+----------+-----------+--------------------+------+---------+

In [ ]:
# write data as hive table
# This doesn't work, probably because the default catalog is unity catalog and not hive metastore. So, we need to set the catalog to hive_metastore first.
# df_sales.write.format("hive").mode("overwrite").option("path","/Volumes/workspace/default/data/output/sales_hive/").save()
# df_sales.write.mode("overwrite").saveAsTable("workspace.default.sales_hive")

In [ ]:
# spark.sql("UPDATE workspace.default.sales_parquet SET AMOUNT = 0 WHERE trx_id = '1995601912'")

In [44]:
df_sales.write.format("delta").mode("overwrite").option("path","/Volumes/workspace/default/data/output/sales_delta").save()
df_sales.write.format("delta").mode("overwrite").saveAsTable("workspace.default.sales_delta")

In [45]:
spark.sql("SHOW TABLES IN default").show()

+--------+-------------+-----------+
|database|    tableName|isTemporary|
+--------+-------------+-----------+
| default|  sales_delta|      false|
| default|sales_parquet|      false|
+--------+-------------+-----------+

In [46]:
spark.sql('DESCRIBE EXTENDED sales_delta').show()

+--------------------+--------------------+-------+
|            col_name|           data_type|comment|
+--------------------+--------------------+-------+
|       transacted_at|           timestamp|   NULL|
|              trx_id|                 int|   NULL|
|         retailer_id|                 int|   NULL|
|         description|              string|   NULL|
|              amount|              double|   NULL|
|             city_id|                 int|   NULL|
|                    |                    |       |
|# Delta Statistic...|                    |       |
|        Column Names|description, trx_...|       |
|Column Selection ...|            first-32|       |
|                    |                    |       |
|# Detailed Table ...|                    |       |
|             Catalog|           workspace|       |
|            Database|             default|       |
|               Table|         sales_delta|       |
|        Created Time|Thu Sep 17 01:32:...|       |
|         Last Access|             UNKNOWN|       |
|          Created By|              Spark |       |
|          Statistics|17808571 bytes, 1...|       |
|                Type|             MANAGED|       |
+--------------------+--------------------+-------+
only showing top 20 rows

In [50]:
# View files for delta
# dbutils.fs.ls("/Volumes/workspace/default/data/output/sales_delta/")
files = w.files.list_directory_contents(directory_path="/Volumes/workspace/default/data/output/sales_delta/_delta_log/")
for f in files:
	print(f"Path: {f.path}, Name: {f.name}, Size: {f.file_size} bytes, Last Modified: {f.last_modified}")

Path: /Volumes/workspace/default/data/output/sales_delta/_delta_log/00000000000000000000.crc, Name: 00000000000000000000.crc, Size: 3441 bytes, Last Modified: 1789608758000
Path: /Volumes/workspace/default/data/output/sales_delta/_delta_log/00000000000000000000.json, Name: 00000000000000000000.json, Size: 2494 bytes, Last Modified: 1789608758000
Path: /Volumes/workspace/default/data/output/sales_delta/_delta_log/_staged_commits/, Name: _staged_commits, Size: None bytes, Last Modified: None

In [53]:
dbutils.fs.head("/Volumes/workspace/default/data/output/sales_delta/_delta_log/00000000000000000000.json")

'{"commitInfo":{"timestamp":1789608756849,"userId":"76765636852086","userName":"mohit_kumar_singh@yahoo.com","operation":"WRITE","operationParameters":{"mode":"Overwrite","statsOnLoad":false,"partitionBy":"[]"},"queryHistoryStatementId":"a0c10c76-b5cc-4126-9e2c-4bc4d7f66c17","clusterId":"0917-012730-io408p4f-v2n","isolationLevel":"WriteSerializable","isBlindAppend":false,"dataChange":true,"operationMetrics":{"numFiles":"1","numRemovedFiles":"0","numRemovedBytes":"0","numDeletionVectorsRemoved":"0","numOutputRows":"1102576","numOutputBytes":"27297385"},"tags":{"noRowsCopied":"true","restoresDeletedRows":"false"},"engineInfo":"Databricks-Runtime/19.6.x-aarch64-photon-scala2.13","txnId":"930fd207-cbd1-45a1-b4fc-bcddb282b689"}}\n{"metaData":{"id":"fc998408-de27-43fe-84e1-07585c837ade","format":{"provider":"parquet","options":{}},"schemaString":"{\\"type\\":\\"struct\\",\\"fields\\":[{\\"name\\":\\"transacted_at\\",\\"type\\":\\"timestamp\\",\\"nullable\\":true,\\"metadata\\":{}},{\\"name\\":\\"trx_id\\",\\"type\\":\\"integer\\",\\"nullable\\":true,\\"metadata\\":{}},{\\"name\\":\\"retailer_id\\",\\"type\\":\\"integer\\",\\"nullable\\":true,\\"metadata\\":{}},{\\"name\\":\\"description\\",\\"type\\":\\"string\\",\\"nullable\\":true,\\"metadata\\":{}},{\\"name\\":\\"amount\\",\\"type\\":\\"double\\",\\"nullable\\":true,\\"metadata\\":{}},{\\"name\\":\\"city_id\\",\\"type\\":\\"integer\\",\\"nullable\\":true,\\"metadata\\":{}}]}","partitionColumns":[],"configuration":{"delta.enableDeletionVectors":"true"},"createdTime":1789608752174}}\n{"protocol":{"minReaderVersion":3,"minWriterVersion":7,"readerFeatures":["deletionVectors"],"writerFeatures":["deletionVectors","appendOnly","invariants"]}}\n{"add":{"path":"part-00000-74d4c6df-e71e-4582-bc0b-7ab3b3ace1d8.c000.snappy.parquet","partitionValues":{},"size":27297385,"modificationTime":1789608755000,"dataChange":true,"stats":"{\\"numRecords\\":1102576,\\"minValues\\":{\\"transacted_at\\":\\"2017-01-01T19:00:00.000Z\\",\\"trx_id\\":20,\\"retailer_id\\":9225731,\\"description\\":\\"7-Eleven\\",\\"amount\\":0.0,\\"city_id\\":7441192},\\"maxValues\\":{\\"transacted_at\\":\\"2017-12-31T23:00:00.000Z\\",\\"trx_id\\":2147474653,\\"retailer_id\\":2145070162,\\"description\\":\\"unkn  ppd id: 999978\\",\\"amount\\":2999.95,\\"city_id\\":2130657559},\\"nullCount\\":{\\"transacted_at\\":0,\\"trx_id\\":0,\\"retailer_id\\":0,\\"description\\":0,\\"amount\\":0,\\"city_id\\":1},\\"tightBounds\\":true}","tags":{"INSERTION_TIME":"1789608755000000","MIN_INSERTION_TIME":"1789608755000000","MAX_INSERTION_TIME":"1789608755000000","OPTIMIZE_TARGET_SIZE":"268435456"}}}\n'

In [54]:
# spark.sql("SELECT * FROM workspace.default.sales_delta").show()
display(spark.sql("SELECT * FROM workspace.default.sales_delta"))

DataFrame[transacted_at: timestamp, trx_id: int, retailer_id: int, description: string, amount: double, city_id: int]

In [55]:
spark.sql("DESCRIBE HISTORY workspace.default.sales_delta").show()

+-------+-------------------+--------------+--------------------+--------------------+--------------------+----+--------+-----------------------+--------------------+-----------+-----------------+-------------+--------------------+------------+--------------------+
|version|          timestamp|        userId|            userName|           operation| operationParameters| job|notebook|queryHistoryStatementId|           clusterId|readVersion|   isolationLevel|isBlindAppend|    operationMetrics|userMetadata|          engineInfo|
+-------+-------------------+--------------+--------------------+--------------------+--------------------+----+--------+-----------------------+--------------------+-----------+-----------------+-------------+--------------------+------------+--------------------+
|      0|2026-09-17 01:32:45|76765636852086|mohit_kumar_singh...|CREATE OR REPLACE...|{isV1SaveAsTableO...|NULL|    NULL|   156b8977-eaaf-423...|0917-012730-io408...|       NULL|WriteSerializable|        false|{numFiles -> 1, n...|        NULL|Databricks-Runtim...|
+-------+-------------------+--------------+--------------------+--------------------+--------------------+----+--------+-----------------------+--------------------+-----------+-----------------+-------------+--------------------+------------+--------------------+

In [56]:
spark.sql("UPDATE workspace.default.sales_delta SET AMOUNT = 0 WHERE trx_id = '1995601912'")

DataFrame[num_affected_rows: bigint]

In [57]:
spark.sql("SELECT * FROM workspace.default.sales_delta WHERE trx_id = '1995601912'").show()

+-------------------+----------+-----------+--------------------+------+---------+
|      transacted_at|    trx_id|retailer_id|         description|amount|  city_id|
+-------------------+----------+-----------+--------------------+------+---------+
|2017-11-24 19:00:00|1995601912| 2077350195|Walgreen       11-25|   0.0|216510442|
+-------------------+----------+-----------+--------------------+------+---------+

In [ ]:
dbutils.fs.ls("/Volumes/workspace/default/data/output/sales_delta/")

[FileInfo(path='/Volumes/workspace/default/data/output/sales_delta/part-00000-74d4c6df-e71e-4582-bc0b-7ab3b3ace1d8.c000.snappy.parquet', name='part-00000-74d4c6df-e71e-4582-bc0b-7ab3b3ace1d8.c000.snappy.parquet', size=27297385, modificationTime=1789608755000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta/_delta_log/', name='', size=None, modificationTime=None)]

In [ ]:
dbutils.fs.ls("/Volumes/workspace/default/data/output/sales_delta/_delta_log/")
# Don't see extra json for update command I just executed

[FileInfo(path='/Volumes/workspace/default/data/output/sales_delta/_delta_log/00000000000000000000.crc', name='00000000000000000000.crc', size=3441, modificationTime=1789608758000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta/_delta_log/00000000000000000000.json', name='00000000000000000000.json', size=2494, modificationTime=1789608758000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta/_delta_log/_staged_commits/', name='', size=None, modificationTime=None)]

In [65]:
display(spark.sql("DESCRIBE HISTORY sales_delta"))

DataFrame[version: bigint, timestamp: timestamp, userId: string, userName: string, operation: string, operationParameters: map<string,string>, job: struct<jobId:string,jobName:string,jobRunId:string,runId:string,jobOwnerId:string,triggerType:string,workspaceId:string>, notebook: struct<notebookId:string>, queryHistoryStatementId: string, clusterId: string, readVersion: bigint, isolationLevel: string, isBlindAppend: boolean, operationMetrics: map<string,string>, userMetadata: string, engineInfo: string]

In [ ]:
# Read a particular version - pyspark api
# df_sales_delta = spark.read.table("workspace.default.sales_delta")
df_sales_delta = spark.read.format("delta").load("/Volumes/workspace/default/data/output/sales_delta")

display(df_sales_delta)

DataFrame[transacted_at: timestamp, trx_id: int, retailer_id: int, description: string, amount: double, city_id: int]

In [74]:
df_sales_delta = spark.read.table("workspace.default.sales_delta@v0")
# display(df_sales_delta)
display(df_sales_delta.where("trx_id = '1995601912'"))

DataFrame[transacted_at: timestamp, trx_id: int, retailer_id: int, description: string, amount: double, city_id: int]

In [73]:
df_sales_delta = spark.read.table("workspace.default.sales_delta@v1")
# display(df_sales_delta)
display(df_sales_delta.where("trx_id = '1995601912'"))

DataFrame[transacted_at: timestamp, trx_id: int, retailer_id: int, description: string, amount: double, city_id: int]

In [76]:
# Read version in SQL queries
spark.sql("SELECT * FROM workspace.default.sales_delta@v0 WHERE trx_id = '1995601912'").show()

+-------------------+----------+-----------+--------------------+------+---------+
|      transacted_at|    trx_id|retailer_id|         description|amount|  city_id|
+-------------------+----------+-----------+--------------------+------+---------+
|2017-11-24 19:00:00|1995601912| 2077350195|Walgreen       11-25|197.23|216510442|
+-------------------+----------+-----------+--------------------+------+---------+

In [77]:
spark.sql("SELECT * FROM workspace.default.sales_delta@v1 WHERE trx_id = '1995601912'").show()

+-------------------+----------+-----------+--------------------+------+---------+
|      transacted_at|    trx_id|retailer_id|         description|amount|  city_id|
+-------------------+----------+-----------+--------------------+------+---------+
|2017-11-24 19:00:00|1995601912| 2077350195|Walgreen       11-25|   0.0|216510442|
+-------------------+----------+-----------+--------------------+------+---------+

In [78]:
# Schema evolution with mergeSchema option
df_new = spark.sql("SELECT *, current_timestamp() AS current_time FROM workspace.default.sales_delta WHERE trx_id = '1995601912'")
df_new.show()

+-------------------+----------+-----------+--------------------+------+---------+--------------------+
|      transacted_at|    trx_id|retailer_id|         description|amount|  city_id|        current_time|
+-------------------+----------+-----------+--------------------+------+---------+--------------------+
|2017-11-24 19:00:00|1995601912| 2077350195|Walgreen       11-25|   0.0|216510442|2026-09-17 09:34:...|
+-------------------+----------+-----------+--------------------+------+---------+--------------------+

In [79]:
# Append data to existing delta table
df_new.write.format("delta").mode("append").option("mergeSchema", True).option("path", "/Volumes/workspace/default/data/output/sales_delta").saveAsTable("workspace.default.sales_delta")

In [3]:
# Reading delta tables using delta libraries
from delta import DeltaTable
dt = DeltaTable.forName(spark, "workspace.default.sales_delta")

# dt.history().show()
display(dt.history())

DataFrame[version: bigint, timestamp: timestamp, userId: string, userName: string, operation: string, operationParameters: map<string,string>, job: struct<jobId:string,jobName:string,jobRunId:string,runId:string,jobOwnerId:string,triggerType:string,workspaceId:string>, notebook: struct<notebookId:string>, queryHistoryStatementId: string, clusterId: string, readVersion: bigint, isolationLevel: string, isBlindAppend: boolean, operationMetrics: map<string,string>, userMetadata: string, engineInfo: string]

In [83]:
# spark.sql("SELECT * FROM workspace.default.sales_delta WHERE trx_id = '1995601912'").show()
spark.sql("SELECT * FROM workspace.default.sales_delta").show()

+-------------------+----------+-----------+--------------------+-------+----------+------------+
|      transacted_at|    trx_id|retailer_id|         description| amount|   city_id|current_time|
+-------------------+----------+-----------+--------------------+-------+----------+------------+
|2017-11-24 19:00:00|1734117021|  644879053|unkn    ppd id: 7...|   8.58| 930259917|        NULL|
|2017-11-24 19:00:00|1734117022|  847200066|Wal-Mart  ppd id:...|1737.26|1646415505|        NULL|
|2017-11-24 19:00:00|1734117030| 1953761884|Home Depot     pp...|  384.5| 287177635|        NULL|
|2017-11-24 19:00:00|1734117089| 1898522855| Target        11-25|  66.33|1855530529|        NULL|
|2017-11-24 19:00:00|1734117117|  997626433|Sears  ppd id: 85...| 298.87| 957346984|        NULL|
|2017-11-24 19:00:00|1734117123| 1953761884|unkn   ppd id: 15...|  19.55|  45522086|        NULL|
|2017-11-24 19:00:00|1734117152| 1429095612|Ikea     arc id: ...|   9.39|1268541279|        NULL|
|2017-11-24 19:00:00|1734117153|  847200066|unkn        Kings...|2907.57|1483931123|        NULL|
|2017-11-24 19:00:00|1734117212| 1996661856|unkn    ppd id: 4...| 140.38| 336763936|        NULL|
|2017-11-24 19:00:00|1734117241|  486576507|              iTunes|2912.67|1663872965|        NULL|
|2017-11-24 19:00:00|2076947148|  847200066|Wal-Mart         ...|  62.83|1556600840|        NULL|
|2017-11-24 19:00:00|2076947147|  562903918|McDonald's    ccd...|  31.37| 930259917|        NULL|
|2017-11-24 19:00:00|2076947146|  511877722|unkn     ccd id: ...|1915.35|1698762556|        NULL|
|2017-11-24 19:00:00|2076947113| 1996661856|AutoZone  arc id:...| 1523.6|1759612211|        NULL|
|2017-11-24 19:00:00|2076947018|  902350112|DineEquity    arc...|  22.28|2130657559|        NULL|
|2017-11-24 19:00:00|2076946994| 1898522855|Target    ppd id:...|2589.93|2074005445|        NULL|
|2017-11-24 19:00:00|2076946985|  847200066|Wal-Mart    ppd i...|   42.2| 459344513|        NULL|
|2017-11-24 19:00:00|2076946960|  386167994|Wendy's  ppd id: ...|  14.62| 352952442|        NULL|
|2017-11-24 19:00:00|2076946954|  486576507|iTunes     ppd id...|  37.42| 485114748|        NULL|
|2017-11-24 19:00:00|2076946899|  644879053|unkn     ccd id: ...|  91.91|2068475652|        NULL|
+-------------------+----------+-----------+--------------------+-------+----------+------------+
only showing top 20 rows

In [5]:
# Converting a parquet table to delta table - check and convert
# DeltaTable.isDeltaTable(spark, "/Volumes/workspace/default/data/output/sales_parquet")
DeltaTable.convertToDelta(spark, "parquet.`/Volumes/workspace/default/data/output/sales_parquet`")

In [6]:
dbutils.fs.ls("/Volumes/workspace/default/data/output/sales_parquet")

[FileInfo(path='/Volumes/workspace/default/data/output/sales_parquet/_SUCCESS', name='_SUCCESS', size=0, modificationTime=1789593929000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_parquet/_committed_498013408330543316', name='_committed_498013408330543316', size=123, modificationTime=1789593928000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_parquet/_started_498013408330543316', name='_started_498013408330543316', size=0, modificationTime=1789593927000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_parquet/part-00000-tid-498013408330543316-056f8376-b6fd-4e93-9cd2-4c06d60f6533-133-1.c000.snappy.parquet', name='part-00000-tid-498013408330543316-056f8376-b6fd-4e93-9cd2-4c06d60f6533-133-1.c000.snappy.parquet', size=27297385, modificationTime=1789593928000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_parquet/_delta_log/', name='', size=None, modificationTime=None)]

In [9]:
display(spark.sql("DESCRIBE EXTENDED sales_parquet"))

DataFrame[col_name: string, data_type: string, comment: string]

In [8]:
# convert metadeta to delta as well
spark.sql("CONVERT TO DELTA sales_parquet")

DataFrame[]

In [11]:
# revert back to previous version of delta table
spark.sql("RESTORE TABLE workspace.default.sales_delta TO VERSION AS OF 1")

DataFrame[table_size_after_restore: bigint, num_of_files_after_restore: bigint, num_removed_files: bigint, num_restored_files: bigint, removed_files_size: bigint, restored_files_size: bigint]

In [12]:
display(spark.sql("DESCRIBE HISTORY workspace.default.sales_delta"))

DataFrame[version: bigint, timestamp: timestamp, userId: string, userName: string, operation: string, operationParameters: map<string,string>, job: struct<jobId:string,jobName:string,jobRunId:string,runId:string,jobOwnerId:string,triggerType:string,workspaceId:string>, notebook: struct<notebookId:string>, queryHistoryStatementId: string, clusterId: string, readVersion: bigint, isolationLevel: string, isBlindAppend: boolean, operationMetrics: map<string,string>, userMetadata: string, engineInfo: string]

In [15]:
# Verifying
display(spark.sql("SELECT * FROM workspace.default.sales_delta@v0 WHERE trx_id = '1995601912'"))

DataFrame[transacted_at: timestamp, trx_id: int, retailer_id: int, description: string, amount: double, city_id: int]

In [19]:
dbutils.fs.ls("/Volumes/workspace/default/data/output/sales_delta")

[FileInfo(path='/Volumes/workspace/default/data/output/sales_delta/part-00000-74d4c6df-e71e-4582-bc0b-7ab3b3ace1d8.c000.snappy.parquet', name='part-00000-74d4c6df-e71e-4582-bc0b-7ab3b3ace1d8.c000.snappy.parquet', size=27297385, modificationTime=1789608755000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta/_delta_log/', name='', size=None, modificationTime=None)]

In [ ]:
# remove all versions of delta table
spark.sql("""
    ALTER TABLE workspace.default.sales_delta
    SET TBLPROPERTIES (
      'delta.logRetentionDuration' = 'interval 0 hours',
      'delta.deletedFileRetentionDuration' = 'interval 0 hours'
    )
""")

DataFrame[]

In [27]:
# remove all versions of delta table
# spark.conf.set("spark.databricks.delta.retentionDurationCheck.enabled", "false")
# spark.sql("SET spark.databricks.delta.retentionDurationCheck.enabled = false")
dt = DeltaTable.forName(spark, "workspace.default.sales_delta")
dt.vacuum(0)
# spark.sql("VACUUM workspace.default.sales_delta RETAIN 0 HOURS")

In [30]:
# check if the versions are removed
dbutils.fs.ls("/Volumes/workspace/default/data/output/sales_delta")

[FileInfo(path='/Volumes/workspace/default/data/output/sales_delta/part-00000-74d4c6df-e71e-4582-bc0b-7ab3b3ace1d8.c000.snappy.parquet', name='part-00000-74d4c6df-e71e-4582-bc0b-7ab3b3ace1d8.c000.snappy.parquet', size=27297385, modificationTime=1789608755000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta/_delta_log/', name='', size=None, modificationTime=None)]

In [ ]:
display(spark.sql("DESCRIBE HISTORY workspace.default.sales_delta"))

DataFrame[version: bigint, timestamp: timestamp, userId: string, userName: string, operation: string, operationParameters: map<string,string>, job: struct<jobId:string,jobName:string,jobRunId:string,runId:string,jobOwnerId:string,triggerType:string,workspaceId:string>, notebook: struct<notebookId:string>, queryHistoryStatementId: string, clusterId: string, readVersion: bigint, isolationLevel: string, isBlindAppend: boolean, operationMetrics: map<string,string>, userMetadata: string, engineInfo: string]

In [34]:
display(spark.sql("SELECT * FROM workspace.default.sales_delta@v6 WHERE trx_id = '1995601912'"))
# the versions are there as per metadeta but the files are removed from the storage. So, the data is not available for that version. This is cause we vaccumed the delta table and removed the files from storage. Vaccume removes all the time travel information.

DataFrame[transacted_at: timestamp, trx_id: int, retailer_id: int, description: string, amount: double, city_id: int]

In [ ]:
# Converting back to parquet
df_sales_delta = spark.read.table("workspace.default.sales_delta@v6")
# Write as standard Parquet
# df_sales_delta.write.mode("overwrite").format("parquet").save("/Volumes/workspace/default/output_data/sales_parquet")

## Data Skipping and Z-Ordering in Delta Lake Tables | Optimize & Data Compaction Delta Lake Tables

In [3]:
# Dataset
dbutils.fs.ls("/Volumes/samples/databricks/datasets/definitive-guide/data/retail-data/all/online-retail-dataset.csv")

[FileInfo(path='/Volumes/samples/databricks/datasets/definitive-guide/data/retail-data/all/online-retail-dataset.csv', name='online-retail-dataset.csv', size=45038760, modificationTime='Wed, 24 Jun 2026 17:23:52 GMT')]

In [4]:
display(dbutils.fs.head("/Volumes/samples/databricks/datasets/definitive-guide/data/retail-data/all/online-retail-dataset.csv"))

'InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country\n536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850,United Kingdom\n536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850,United Kingdom\n536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850,United Kingdom\n536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850,United Kingdom\n536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850,United Kingdom\n536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12/1/2010 8:26,7.65,17850,United Kingdom\n536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12/1/2010 8:26,4.25,17850,United Kingdom\n536366,22633,HAND WARMER UNION JACK,6,12/1/2010 8:28,1.85,17850,United Kingdom\n536366,22632,HAND WARMER RED POLKA DOT,6,12/1/2010 8:28,1.85,17850,United Kingdom\n536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,12/1/2010 8:34,1.69,13047,United Kingdom\n536367,22745,POPPY\'S PLAYHOUSE BEDROOM ,6,12/1/2010 8:34,2.1,13047,United Kingdom\n536367,22748,POPPY\'S PLAYHOUSE KITCHEN,6,12/1/2010 8:34,2.1,13047,United Kingdom\n536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,12/1/2010 8:34,3.75,13047,United Kingdom\n536367,22310,IVORY KNITTED MUG COSY ,6,12/1/2010 8:34,1.65,13047,United Kingdom\n536367,84969,BOX OF 6 ASSORTED COLOUR TEASPOONS,6,12/1/2010 8:34,4.25,13047,United Kingdom\n536367,22623,BOX OF VINTAGE JIGSAW BLOCKS ,3,12/1/2010 8:34,4.95,13047,United Kingdom\n536367,22622,BOX OF VINTAGE ALPHABET BLOCKS,2,12/1/2010 8:34,9.95,13047,United Kingdom\n536367,21754,HOME BUILDING BLOCK WORD,3,12/1/2010 8:34,5.95,13047,United Kingdom\n536367,21755,LOVE BUILDING BLOCK WORD,3,12/1/2010 8:34,5.95,13047,United Kingdom\n536367,21777,RECIPE BOX WITH METAL HEART,4,12/1/2010 8:34,7.95,13047,United Kingdom\n536367,48187,DOORMAT NEW ENGLAND,4,12/1/2010 8:34,7.95,13047,United Kingdom\n536368,22960,JAM MAKING SET WITH JARS,6,12/1/2010 8:34,4.25,13047,United Kingdom\n536368,22913,RED COAT RACK PARIS FASHION,3,12/1/2010 8:34,4.95,13047,United Kingdom\n536368,22912,YELLOW COAT RACK PARIS FASHION,3,12/1/2010 8:34,4.95,13047,United Kingdom\n536368,22914,BLUE COAT RACK PARIS FASHION,3,12/1/2010 8:34,4.95,13047,United Kingdom\n536369,21756,BATH BUILDING BLOCK WORD,3,12/1/2010 8:35,5.95,13047,United Kingdom\n536370,22728,ALARM CLOCK BAKELIKE PINK,24,12/1/2010 8:45,3.75,12583,France\n536370,22727,ALARM CLOCK BAKELIKE RED ,24,12/1/2010 8:45,3.75,12583,France\n536370,22726,ALARM CLOCK BAKELIKE GREEN,12,12/1/2010 8:45,3.75,12583,France\n536370,21724,PANDA AND BUNNIES STICKER SHEET,12,12/1/2010 8:45,0.85,12583,France\n536370,21883,STARS GIFT TAPE ,24,12/1/2010 8:45,0.65,12583,France\n536370,10002,INFLATABLE POLITICAL GLOBE ,48,12/1/2010 8:45,0.85,12583,France\n536370,21791,VINTAGE HEADS AND TAILS CARD GAME ,24,12/1/2010 8:45,1.25,12583,France\n536370,21035,SET/2 RED RETROSPOT TEA TOWELS ,18,12/1/2010 8:45,2.95,12583,France\n536370,22326,ROUND SNACK BOXES SET OF4 WOODLAND ,24,12/1/2010 8:45,2.95,12583,France\n536370,22629,SPACEBOY LUNCH BOX ,24,12/1/2010 8:45,1.95,12583,France\n536370,22659,LUNCH BOX I LOVE LONDON,24,12/1/2010 8:45,1.95,12583,France\n536370,22631,CIRCUS PARADE LUNCH BOX ,24,12/1/2010 8:45,1.95,12583,France\n536370,22661,CHARLOTTE BAG DOLLY GIRL DESIGN,20,12/1/2010 8:45,0.85,12583,France\n536370,21731,RED TOADSTOOL LED NIGHT LIGHT,24,12/1/2010 8:45,1.65,12583,France\n536370,22900, SET 2 TEA TOWELS I LOVE LONDON ,24,12/1/2010 8:45,2.95,12583,France\n536370,21913,VINTAGE SEASIDE JIGSAW PUZZLES,12,12/1/2010 8:45,3.75,12583,France\n536370,22540,MINI JIGSAW CIRCUS PARADE ,24,12/1/2010 8:45,0.42,12583,France\n536370,22544,MINI JIGSAW SPACEBOY,24,12/1/2010 8:45,0.42,12583,France\n536370,22492,MINI PAINT SET VINTAGE ,36,12/1/2010 8:45,0.65,12583,France\n536370,POST,POSTAGE,3,12/1/2010 8:45,18,12583,France\n536371,22086,PAPER CHAIN KIT 50\'S CHRISTMAS ,80,12/1/2010 9:00,2.55,13748,United Kingdom\n536372,22632,HAND WARMER RED POLKA DOT,6,12/1/2010 9:01,1.85,17850,United Kingdom\n536372,22633,HAND WARMER UNION JACK,6,12/1/2010 9:01,1.85,17850,United Kingdom\n536373,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 9:02,2.55,17850,United Kingdom\n536373,71053,WHITE METAL LANTERN,6,12/1/2010 9:02,3.39,17850,United Kingdom\n536373,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 9:02,2.75,17850,United Kingdom\n536373,20679,EDWARDIAN PARASOL RED,6,12/1/2010 9:02,4.95,17850,United Kingdom\n536373,37370,RETRO COFFEE MUGS ASSORTED,6,12/1/2010 9:02,1.06,17850,United Kingdom\n536373,21871,SAVE THE PLANET MUG,6,12/1/2010 9:02,1.06,17850,United Kingdom\n536373,21071,VINTAGE BILLBOARD DRINK ME MUG,6,12/1/2010 9:02,1.06,17850,United Kingdom\n536373,21068,VINTAGE BILLBOARD LOVE/HATE MUG,6,12/1/2010 9:02,1.06,17850,United Kingdom\n536373,82483,WOOD 2 DRAWER CABINET WHITE FINISH,2,12/1/2010 9:02,4.95,17850,United Kingdom\n536373,82486,WOOD S/3 CABINET ANT WHITE FINISH,4,12/1/2010 9:02,6.95,17850,United Kingdom\n536373,82482,WOODEN PICTURE FRAME WHITE FINISH,6,12/1/2010 9:02,2.1,17850,United Kingdom\n536373,82494L,WOODEN FRAME ANTIQUE WHITE ,6,12/1/2010 9:02,2.55,17850,United Kingdom\n536373,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 9:02,3.39,17850,United Kingdom\n536373,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 9:02,3.39,17850,United Kingdom\n536373,22752,SET 7 BABUSHKA NESTING BOXES,2,12/1/2010 9:02,7.65,17850,United Kingdom\n536373,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12/1/2010 9:02,4.25,17850,United Kingdom\n536374,21258,VICTORIAN SEWING BOX LARGE,32,12/1/2010 9:09,10.95,15100,United Kingdom\n536375,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 9:32,2.55,17850,United Kingdom\n536375,71053,WHITE METAL LANTERN,6,12/1/2010 9:32,3.39,17850,United Kingdom\n536375,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 9:32,2.75,17850,United Kingdom\n536375,20679,EDWARDIAN PARASOL RED,6,12/1/2010 9:32,4.95,17850,United Kingdom\n536375,37370,RETRO COFFEE MUGS ASSORTED,6,12/1/2010 9:32,1.06,17850,United Kingdom\n536375,21871,SAVE THE PLANET MUG,6,12/1/2010 9:32,1.06,17850,United Kingdom\n536375,21071,VINTAGE BILLBOARD DRINK ME MUG,6,12/1/2010 9:32,1.06,17850,United Kingdom\n536375,21068,VINTAGE BILLBOARD LOVE/HATE MUG,6,12/1/2010 9:32,1.06,17850,United Kingdom\n536375,82483,WOOD 2 DRAWER CABINET WHITE FINISH,2,12/1/2010 9:32,4.95,17850,United Kingdom\n536375,82486,WOOD S/3 CABINET ANT WHITE FINISH,4,12/1/2010 9:32,6.95,17850,United Kingdom\n536375,82482,WOODEN PICTURE FRAME WHITE FINISH,6,12/1/2010 9:32,2.1,17850,United Kingdom\n536375,82494L,WOODEN FRAME ANTIQUE WHITE ,6,12/1/2010 9:32,2.55,17850,United Kingdom\n536375,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 9:32,3.39,17850,United Kingdom\n536375,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 9:32,3.39,17850,United Kingdom\n536375,22752,SET 7 BABUSHKA NESTING BOXES,2,12/1/2010 9:32,7.65,17850,United Kingdom\n536375,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12/1/2010 9:32,4.25,17850,United Kingdom\n536376,22114,HOT WATER BOTTLE TEA AND SYMPATHY,48,12/1/2010 9:32,3.45,15291,United Kingdom\n536376,21733,RED HANGING HEART T-LIGHT HOLDER,64,12/1/2010 9:32,2.55,15291,United Kingdom\n536377,22632,HAND WARMER RED POLKA DOT,6,12/1/2010 9:34,1.85,17850,United Kingdom\n536377,22633,HAND WARMER UNION JACK,6,12/1/2010 9:34,1.85,17850,United Kingdom\n536378,22386,JUMBO BAG PINK POLKADOT,10,12/1/2010 9:37,1.95,14688,United Kingdom\n536378,85099C,JUMBO  BAG BAROQUE BLACK WHITE,10,12/1/2010 9:37,1.95,14688,United Kingdom\n536378,21033,JUMBO BAG CHARLIE AND LOLA TOYS,10,12/1/2010 9:37,2.95,14688,United Kingdom\n536378,20723,STRAWBERRY CHARLOTTE BAG,10,12/1/2010 9:37,0.85,14688,United Kingdom\n536378,84997B,RED 3 PIECE RETROSPOT CUTLERY SET,12,12/1/2010 9:37,3.75,14688,United Kingdom\n536378,84997C,BLUE 3 PIECE POLKADOT CUTLERY SET,6,12/1/2010 9:37,3.75,14688,United Kingdom\n536378,21094,SET/6 RED SPOTTY PAPER PLATES,12,12/1/2010 9:37,0.85,14688,United Kingdom\n536378,20725,LUNCH BAG RED RETROSPOT,10,12/1/2010 9:37,1.65,14688,United Kingdom\n536378,21559,STRAWBERRY LUNCH BOX WITH CUTLERY,6,12/1/2010 9:37,2.55,14688,United Kingdom\n536378,22352,LUNCH BOX WITH CUTLERY RETROSPOT ,6,12/1/2010 9:37,2.55,14688,United Kingdom\n536378,21212,PACK OF 72 RETROSPOT CAKE CASES,120,12/1/2010 9:37,0.42,14688,United Kingdom\n536378,21975,PACK OF 60 DINOSAUR CAKE CASES,24,12/1/2010 9:37,0.55,14688,United Kingdom\n536378,21977,PACK OF 60 PINK PAISLEY CAKE CASES,24,12/1/2010 9:37,0.55,14688,United Kingdom\n536378,84991,60 TEATIME FAIRY CAKE CASES,24,12/1/2010 9:37,0.55,14688,United Kingdom\n536378,84519A,TOMATO CHARLIE+LOLA COASTER SET,6,12/1/2010 9:37,2.95,14688,United Kingdom\n536378,85183B,CHARLIE & LOLA WASTEPAPER BIN FLORA,48,12/1/2010 9:37,1.25,14688,United Kingdom\n536378,85071B,RED CHARLIE+LOLA PERSONAL DOORSIGN,96,12/1/2010 9:37,0.38,14688,United Kingdom\n536378,21931,JUMBO STORAGE BAG SUKI,10,12/1/2010 9:37,1.95,14688,United Kingdom\n536378,21929,JUMBO BAG PINK VINTAGE PAISLEY,10,12/1/2010 9:37,1.95,14688,United Kingdom\n536380,22961,JAM MAKING SET PRINTED,24,12/1/2010 9:41,1.45,17809,United Kingdom\n536381,22139,RETROSPOT TEA SET CERAMIC 11 PC ,23,12/1/2010 9:41,4.25,15311,United Kingdom\n536381,84854,GIRLY PINK TOOL SET,5,12/1/2010 9:41,4.95,15311,United Kingdom\n536381,22411,JUMBO SHOPPER VINTAGE RED PAISLEY,10,12/1/2010 9:41,1.95,15311,United Kingdom\n536381,82567,"AIRLINE LOUNGE,METAL SIGN",2,12/1/2010 9:41,2.1,15311,United Kingdom\n536381,21672,WHITE SPOT RED CERAMIC DRAWER KNOB,6,12/1/2010 9:41,1.25,15311,United Kingdom\n536381,22774,RED DRAWER KNOB ACRYLIC EDWARDIAN,24,12/1/2010 9:41,1.25,15311,United Kingdom\n536381,22771,CLEAR DRAWER KNOB ACRYLIC EDWARDIAN,24,12/1/2010 9:41,1.25,15311,United Kingdom\n536381,71270,PHOTO CLIP LINE,1,12/1/2010 9:41,1.25,15311,United Kingdom\n536381,22262,FELT EGG COSY CHICKEN,1,12/1/2010 9:41,0.85,15311,United Kingdom\n536381,22637,PIGGY BANK RETROSPOT ,1,12/1/2010 9:41,2.55,15311,United Kingdom\n536381,21934,SKULL SHOULDER BAG,10,12/1/2010 9:41,1.65,15311,United Kingdom\n536381,21169,YOU\'RE CONFUSING ME METAL SIGN ,3,12/1/2010 9:41,1.69,15311,United Kingdom\n536381,21166,COOK WITH WINE METAL SIGN ,1,12/1/2010 9:41,1.95,15311,United Kingdom\n536381,21175,GIN + TONIC DIET METAL SIGN,2,12/1/2010 9:41,2.1,15311,United Kingdom\n536381,37444A,YELLOW BREAKFAST CUP AND SAUCER,1,12/1/2010 9:41,2.95,15311,United Kingdom\n536381,37444C,PINK BREAKFAST CUP AND SAUCER ,1,12/1/2010 9:41,2.95,15311,United Kingdom\n536381,22086,PAPER CHAIN KIT 50\'S CHRISTMAS ,4,12/1/2010 9:41,2.95,15311,United Kingdom\n536381,22083,PAPER CHAIN KIT RETROSPOT,1,12/1/2010 9:41,2.95,15311,United Kingdom\n536381,84971S,SMALL HEART FLOWERS HOOK ,6,12/1/2010 9:41,0.85,15311,United Kingdom\n536381,71270,PHOTO CLIP LINE,3,12/1/2010 9:41,1.25,15311,United Kingdom\n536381,47580,TEA TIME DES TEA COSY,2,12/1/2010 9:41,2.55,15311,United Kingdom\n536381,22261,FELT EGG COSY WHITE RABBIT ,1,12/1/2010 9:41,0.85,15311,United Kingdom\n536381,84832,ZINC WILLIE WINKIE  CANDLE STICK,1,12/1/2010 9:41,0.85,15311,United Kingdom\n536381,22644,CERAMIC CHERRY CAKE MONEY BANK,1,12/1/2010 9:41,1.45,15311,United Kingdom\n536381,21533,RETROSPOT LARGE MILK JUG,1,12/1/2010 9:41,4.95,15311,United Kingdom\n536381,21557,SET OF 6 FUNKY BEAKERS,2,12/1/2010 9:41,2.95,15311,United Kingdom\n536381,15056BL,EDWARDIAN PARASOL BLACK,2,12/1/2010 9:41,5.95,15311,United Kingdom\n536381,15056N,EDWARDIAN PARASOL NATURAL,2,12/1/2010 9:41,5.95,15311,United Kingdom\n536381,22646,CERAMIC STRAWBERRY CAKE MONEY BANK,4,12/1/2010 9:41,1.45,15311,United Kingdom\n536381,22176,BLUE OWL SOFT TOY,1,12/1/2010 9:41,2.95,15311,United Kingdom\n536381,22438,BALLOON ART MAKE YOUR OWN FLOWERS,1,12/1/2010 9:41,1.95,15311,United Kingdom\n536381,21731,RED TOADSTOOL LED NIGHT LIGHT,2,12/1/2010 9:41,1.65,15311,United Kingdom\n536381,22778,GLASS CLOCHE SMALL,3,12/1/2010 9:41,3.95,15311,United Kingdom\n536381,22719,GUMBALL MONOCHROME COAT RACK,36,12/1/2010 9:41,1.06,15311,United Kingdom\n536381,21523,DOORMAT FANCY FONT HOME SWEET HOME,10,12/1/2010 9:41,6.75,15311,United Kingdom\nC536379,D,Discount,-1,12/1/2010 9:41,27.5,14527,United Kingdom\n536382,10002,INFLATABLE POLITICAL GLOBE ,12,12/1/2010 9:45,0.85,16098,United Kingdom\n536382,21912,VINTAGE SNAKES & LADDERS,8,12/1/2010 9:45,3.75,16098,United Kingdom\n536382,21832,CHOCOLATE CALCULATOR,12,12/1/2010 9:45,1.65,16098,United Kingdom\n536382,22411,JUMBO SHOPPER VINTAGE RED PAISLEY,10,12/1/2010 9:45,1.95,16098,United Kingdom\n536382,22379,RECYCLING BAG RETROSPOT ,10,12/1/2010 9:45,2.1,16098,United Kingdom\n536382,22381,TOY TIDY PINK POLKADOT,50,12/1/2010 9:45,1.85,16098,United Kingdom\n536382,22798,ANTIQUE GLASS DRESSING TABLE POT,8,12/1/2010 9:45,2.95,16098,United Kingdom\n536382,22726,ALARM CLOCK BAKELIKE GREEN,4,12/1/2010 9:45,3.75,16098,United Kingdom\n536382,22926,IVORY GIANT GARDEN THERMOMETER,12,12/1/2010 9:45,5.95,16098,United Kingdom\n536382,22839,3 TIER CAKE TIN GREEN AND CREAM,2,12/1/2010 9:45,14.95,16098,United Kingdom\n536382,22838,3 TIER CAKE TIN RED AND CREAM,2,12/1/2010 9:45,14.95,16098,United Kingdom\n536382,22783,SET 3 WICKER OVAL BASKETS W LIDS,4,12/1/2010 9:45,16.95,16098,United Kingdom\nC536383,35004C,SET OF 3 COLOURED  FLYING DUCKS,-1,12/1/2010 9:49,4.65,15311,United Kingdom\n536384,82484,WOOD BLACK BOARD ANT WHITE FINISH,3,12/1/2010 9:53,6.45,18074,United Kingdom\n536384,84755,COLOUR GLASS T-LIGHT HOLDER HANGING,48,12/1/2010 9:53,0.65,18074,United Kingdom\n536384,22464,HANGING METAL HEART LANTERN,12,12/1/2010 9:53,1.65,18074,United Kingdom\n536384,21324,HANGING MEDINA LANTERN SMALL,6,12/1/2010 9:53,2.95,18074,United Kingdom\n536384,22457,NATURAL SLATE HEART CHALKBOARD ,12,12/1/2010 9:53,2.95,18074,United Kingdom\n536384,22469,HEART OF WICKER SMALL,40,12/1/2010 9:53,1.45,18074,United Kingdom\n536384,22470,HEART OF WICKER LARGE,40,12/1/2010 9:53,2.55,18074,United Kingdom\n536384,22224,WHITE LOVEBIRD LANTERN,6,12/1/2010 9:53,2.95,18074,United Kingdom\n536384,21340,CLASSIC METAL BIRDCAGE PLANT HOLDER,2,12/1/2010 9:53,12.75,18074,United Kingdom\n536384,22189,CREAM HEART CARD HOLDER,4,12/1/2010 9:53,3.95,18074,United Kingdom\n536384,22427,ENAMEL FLOWER JUG CREAM,3,12/1/2010 9:53,5.95,18074,United Kingdom\n536384,22428,ENAMEL FIRE BUCKET CREAM,6,12/1/2010 9:53,6.95,18074,United Kingdom\n536384,22424,ENAMEL BREAD BIN CREAM,8,12/1/2010 9:53,10.95,18074,United Kingdom\n536385,22783,SET 3 WICKER OVAL BASKETS W LIDS,1,12/1/2010 9:56,19.95,17420,United Kingdom\n536385,22961,JAM MAKING SET PRINTED,12,12/1/2010 9:56,1.45,17420,United Kingdom\n536385,22960,JAM MAKING SET WITH JARS,6,12/1/2010 9:56,4.25,17420,United Kingdom\n536385,22663,JUMBO BAG DOLLY GIRL DESIGN,10,12/1/2010 9:56,1.95,17420,United Kingdom\n536385,85049A,TRADITIONAL CHRISTMAS RIBBONS,12,12/1/2010 9:56,1.25,17420,United Kingdom\n536385,22168,ORGANISER WOOD ANTIQUE WHITE ,2,12/1/2010 9:56,8.5,17420,United Kingdom\n536385,22662,LUNCH BAG DOLLY GIRL DESIGN,10,12/1/2010 9:56,1.65,17420,United Kingdom\n536386,84880,WHITE WIRE EGG HOLDER,36,12/1/2010 9:57,4.95,16029,United Kingdom\n536386,85099C,JUMBO  BAG BAROQUE BLACK WHITE,100,12/1/2010 9:57,1.65,16029,United Kingdom\n536386,85099B,JUMBO BAG RED RETROSPOT,100,12/1/2010 9:57,1.65,16029,United Kingdom\n536387,79321,CHILLI LIGHTS,192,12/1/2010 9:58,3.82,16029,United Kingdom\n536387,22780,LIGHT GARLAND BUTTERFILES PINK,192,12/1/2010 9:58,3.37,16029,United Kingdom\n536387,22779,WOODEN OWLS LIGHT GARLAND ,192,12/1/2010 9:58,3.37,16029,United Kingdom\n536387,22466,FAIRY TALE COTTAGE NIGHTLIGHT,432,12/1/2010 9:58,1.45,16029,United Kingdom\n536387,21731,RED TOADSTOOL LED NIGHT LIGHT,432,12/1/2010 9:58,1.25,16029,United Kingdom\n536388,21754,HOME BUILDING BLOCK WORD,3,12/1/2010 9:59,5.95,16250,United Kingdom\n536388,21755,LOVE BUILDING BLOCK WORD,3,12/1/2010 9:59,5.95,16250,United Kingdom\n536388,21523,DOORMAT FANCY FONT HOME SWEET HOME,2,12/1/2010 9:59,7.95,16250,United Kingdom\n536388,21363,HOME SMALL WOOD LETTERS,3,12/1/2010 9:59,4.95,16250,United Kingdom\n536388,21411,GINGHAM HEART  DOORSTOP RED,3,12/1/2010 9:59,4.25,16250,United Kingdom\n536388,22318,FIVE HEART HANGING DECORATION,6,12/1/2010 9:59,2.95,16250,United Kingdom\n536388,22464,HANGING METAL HEART LANTERN,12,12/1/2010 9:59,1.65,16250,United Kingdom\n536388,22915,ASSORTED BOTTLE TOP  MAGNETS ,12,12/1/2010 9:59,0.42,16250,United Kingdom\n536388,22922,FRIDGE MAGNETS US DINER ASSORTED,12,12/1/2010 9:59,0.85,16250,United Kingdom\n536388,22969,HOMEMADE JAM SCENTED CANDLES,12,12/1/2010 9:59,1.45,16250,United Kingdom\n536388,22923,FRIDGE MAGNETS LES ENFANTS ASSORTED,12,12/1/2010 9:59,0.85,16250,United Kingdom\n536388,21115,ROSE CARAVAN DOORSTOP,4,12/1/2010 9:59,6.75,16250,United Kingdom\n536388,22469,HEART OF WICKER SMALL,12,12/1/2010 9:59,1.65,16250,United Kingdom\n536388,22242,5 HOOK HANGER MAGIC TOADSTOOL,12,12/1/2010 9:59,1.65,16250,United Kingdom\n536389,22941,CHRISTMAS LIGHTS 10 REINDEER,6,12/1/2010 10:03,8.5,12431,Australia\n536389,21622,VINTAGE UNION JACK CUSHION COVER,8,12/1/2010 10:03,4.95,12431,Australia\n536389,21791,VINTAGE HEADS AND TAILS CARD GAME ,12,12/1/2010 10:03,1.25,12431,Australia\n536389,35004C,SET OF 3 COLOURED  FLYING DUCKS,6,12/1/2010 10:03,5.45,12431,Australia\n536389,35004G,SET OF 3 GOLD FLYING DUCKS,4,12/1/2010 10:03,6.35,12431,Australia\n536389,85014B,RED RETROSPOT UMBRELLA,6,12/1/2010 10:03,5.95,12431,Australia\n536389,85014A,BLACK/BLUE POLKADOT UMBRELLA,3,12/1/2010 10:03,5.95,12431,Australia\n536389,22193,RED DINER WALL CLOCK,2,12/1/2010 10:03,8.5,12431,Australia\n536389,22726,ALARM CLOCK BAKELIKE GREEN,4,12/1/2010 10:03,3.75,12431,Australia\n536389,22727,ALARM CLOCK BAKELIKE RED ,4,12/1/2010 10:03,3.75,12431,Australia\n536389,22192,BLUE DINER WALL CLOCK,2,12/1/2010 10:03,8.5,12431,Australia\n536389,22191,IVORY DINER WALL CLOCK,2,12/1/2010 10:03,8.5,12431,Australia\n536389,22195,LARGE HEART MEASURING SPOONS,24,12/1/2010 10:03,1.65,12431,Australia\n536389,22196,SMALL HEART MEASURING SPOONS,24,12/1/2010 10:03,0.85,12431,Australia\n536390,22941,CHRISTMAS LIGHTS 10 REINDEER,2,12/1/2010 10:19,8.5,17511,United Kingdom\n536390,22960,JAM MAKING SET WITH JARS,12,12/1/2010 10:19,3.75,17511,United Kingdom\n536390,22961,JAM MAKING SET PRINTED,12,12/1/2010 10:19,1.45,17511,United Kingdom\n536390,22962,JAM JAR WITH PINK LID,48,12/1/2010 10:19,0.72,17511,United Kingdom\n536390,22963,JAM JAR WITH GREEN LID,48,12/1/2010 10:19,0.72,17511,United Kingdom\n536390,22968,ROSE COTTAGE KEEPSAKE BOX ,8,12/1/2010 10:19,8.5,17511,United Kingdom\n536390,84970S,HANGING HEART ZINC T-LIGHT HOLDER,144,12/1/2010 10:19,0.64,17511,United Kingdom\n536390,22910,PAPER CHAIN KIT VINTAGE CHRISTMAS,40,12/1/2010 10:19,2.55,17511,United Kingdom\n536390,20668,DISCO BALL CHRISTMAS DECORATION,288,12/1/2010 10:19,0.1,17511,United Kingdom\n536390,85123A,WHITE HANGING HEART T-LIGHT HOLDER,64,12/1/2010 10:19,2.55,17511,United Kingdom\n536390,22197,SMALL POPCORN HOLDER,100,12/1/2010 10:19,0.72,17511,United Kingdom\n536390,22198,LARGE POPCORN HOLDER ,50,12/1/2010 10:19,1.45,17511,United Kingdom\n536390,21533,RETROSPOT LARGE MILK JUG,12,12/1/2010 10:19,4.25,17511,United Kingdom\n536390,21080,SET/20 RED RETROSPOT PAPER NAPKINS ,96,12/1/2010 10:19,0.64,17511,United Kingdom\n536390,21094,SET/6 RED SPOTTY PAPER PLATES,96,12/1/2010 10:19,0.64,17511,United Kingdom\n536390,21086,SET/6 RED SPOTTY PAPER CUPS,48,12/1/2010 10:19,0.65,17511,United Kingdom\n536390,21786,POLKADOT RAIN HAT ,144,12/1/2010 10:19,0.32,17511,United Kingdom\n536390,22654,DELUXE SEWING KIT ,40,12/1/2010 10:19,4.95,17511,United Kingdom\n536390,21485,RETROSPOT HEART HOT WATER BOTTLE,24,12/1/2010 10:19,4.25,17511,United Kingdom\n536390,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,24,12/1/2010 10:19,3.39,17511,United Kingdom\n536390,84030E,ENGLISH ROSE HOT WATER BOTTLE,24,12/1/2010 10:19,3.75,17511,United Kingdom\n536390,22174,PHOTO CUBE,48,12/1/2010 10:19,1.48,17511,United Kingdom\n536390,22969,HOMEMADE JAM SCENTED CANDLES,96,12/1/2010 10:19,1.25,17511,United Kingdom\n536390,85099B,JUMBO BAG RED RETROSPOT,100,12/1/2010

In [ ]:
# write the data in the form of delta table
df = spark.read.csv("/Volumes/samples/databricks/datasets/definitive-guide/data/retail-data/all/online-retail-dataset.csv", header=True, inferSchema=True)
df.repartition(16).write.format("delta").mode("overwrite").option("path","/Volumes/workspace/default/data/output/sales_delta_z").save()

In [9]:
df.write.mode("overwrite").saveAsTable("workspace.default.sales_delta_z")
# spark.sql("DROP TABLE IF EXISTS workspace.default.sales_delta_z")

In [4]:
dbutils.fs.ls("/Volumes/workspace/default/data/output/sales_delta_z")

[FileInfo(path='/Volumes/workspace/default/data/output/sales_delta_z/part-00000-a78d839f-2e78-4d95-afd6-ffccd6b012f1.c000.snappy.parquet', name='part-00000-a78d839f-2e78-4d95-afd6-ffccd6b012f1.c000.snappy.parquet', size=526631, modificationTime=1790128297000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta_z/part-00000-b12b62a2-df1a-4fc4-958a-e6270dee062b.c000.snappy.parquet', name='part-00000-b12b62a2-df1a-4fc4-958a-e6270dee062b.c000.snappy.parquet', size=526631, modificationTime=1790243040000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta_z/part-00001-361bd435-3a59-4b91-9fc6-49ff76df90d7.c000.snappy.parquet', name='part-00001-361bd435-3a59-4b91-9fc6-49ff76df90d7.c000.snappy.parquet', size=526840, modificationTime=1790243040000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta_z/part-00001-9cf14554-5ded-4468-9a36-cede8cbf30aa.c000.snappy.parquet', name='part-00001-9cf14554-5ded-4468-9a36-cede8cbf30aa.c000.snappy.parquet', size=526840, modificationTime=1790128297000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta_z/part-00002-9133bf6b-2314-4099-bea5-03a37156f24f.c000.snappy.parquet', name='part-00002-9133bf6b-2314-4099-bea5-03a37156f24f.c000.snappy.parquet', size=525988, modificationTime=1790243040000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta_z/part-00002-e4d554d3-7e6d-4a75-94a2-68ccd1916831.c000.snappy.parquet', name='part-00002-e4d554d3-7e6d-4a75-94a2-68ccd1916831.c000.snappy.parquet', size=525988, modificationTime=1790128297000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta_z/part-00003-73911eae-b028-4679-b542-97595ebc679a.c000.snappy.parquet', name='part-00003-73911eae-b028-4679-b542-97595ebc679a.c000.snappy.parquet', size=526647, modificationTime=1790128297000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta_z/part-00003-ad974214-77b1-4fff-ab50-57dc84913e2c.c000.snappy.parquet', name='part-00003-ad974214-77b1-4fff-ab50-57dc84913e2c.c000.snappy.parquet', size=526647, modificationTime=1790243040000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta_z/part-00004-0d1f9c03-5455-4cc1-b494-a5167e1b3be0.c000.snappy.parquet', name='part-00004-0d1f9c03-5455-4cc1-b494-a5167e1b3be0.c000.snappy.parquet', size=526712, modificationTime=1790243040000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta_z/part-00004-95680018-ce8c-4c67-a07f-c324120fa55d.c000.snappy.parquet', name='part-00004-95680018-ce8c-4c67-a07f-c324120fa55d.c000.snappy.parquet', size=526712, modificationTime=1790128297000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta_z/part-00005-050b4ffd-3c4a-4b0b-b13c-790e33f3461c.c000.snappy.parquet', name='part-00005-050b4ffd-3c4a-4b0b-b13c-790e33f3461c.c000.snappy.parquet', size=526704, modificationTime=1790243040000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta_z/part-00005-f639c8a0-90dd-4ca8-b5b2-8d8c653b7882.c000.snappy.parquet', name='part-00005-f639c8a0-90dd-4ca8-b5b2-8d8c653b7882.c000.snappy.parquet', size=526704, modificationTime=1790128297000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta_z/part-00006-7b0587be-000c-4b39-9e14-d6d35a254b4a.c000.snappy.parquet', name='part-00006-7b0587be-000c-4b39-9e14-d6d35a254b4a.c000.snappy.parquet', size=526578, modificationTime=1790243040000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta_z/part-00006-dbfe4003-9f52-437d-8b99-5565749b2299.c000.snappy.parquet', name='part-00006-dbfe4003-9f52-437d-8b99-5565749b2299.c000.snappy.parquet', size=526578, modificationTime=1790128297000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta_z/part-00007-30034ce3-91b5-4819-adfb-4a33201b6367.c000.snappy.parquet', name='part-00007-30034ce3-91b5-4819-adfb-4a33201b6367.c000.snappy.parquet', size=527140, modificationTime=1790128297000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta_z/part-00007-4a057487-a9a0-4579-bc9a-5da2e2da9741.c000.snappy.parquet', name='part-00007-4a057487-a9a0-4579-bc9a-5da2e2da9741.c000.snappy.parquet', size=527140, modificationTime=1790243040000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta_z/part-00008-b99df6b4-09cf-4b9a-ab2f-45ade67598c1.c000.snappy.parquet', name='part-00008-b99df6b4-09cf-4b9a-ab2f-45ade67598c1.c000.snappy.parquet', size=526539, modificationTime=1790243040000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta_z/part-00008-d1ddbefe-bd11-41f7-beb6-47d3a42b4338.c000.snappy.parquet', name='part-00008-d1ddbefe-bd11-41f7-beb6-47d3a42b4338.c000.snappy.parquet', size=526539, modificationTime=1790128297000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta_z/part-00009-a4c55747-bffa-4a98-ad3d-b00fd2e997de.c000.snappy.parquet', name='part-00009-a4c55747-bffa-4a98-ad3d-b00fd2e997de.c000.snappy.parquet', size=526700, modificationTime=1790243040000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta_z/part-00009-e7069c07-3d6f-402a-8e29-c4da81ab22d4.c000.snappy.parquet', name='part-00009-e7069c07-3d6f-402a-8e29-c4da81ab22d4.c000.snappy.parquet', size=526700, modificationTime=1790128297000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta_z/part-00010-8fada589-d0fa-450a-8dc6-83985e817ece.c000.snappy.parquet', name='part-00010-8fada589-d0fa-450a-8dc6-83985e817ece.c000.snappy.parquet', size=526742, modificationTime=1790128297000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta_z/part-00010-f6e0af21-c376-4a2f-8110-7903eefba4cf.c000.snappy.parquet', name='part-00010-f6e0af21-c376-4a2f-8110-7903eefba4cf.c000.snappy.parquet', size=526742, modificationTime=1790243040000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta_z/part-00011-07a717f2-aa88-4c21-80a4-b2f02b5f3f64.c000.snappy.parquet', name='part-00011-07a717f2-aa88-4c21-80a4-b2f02b5f3f64.c000.snappy.parquet', size=526754, modificationTime=1790243040000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta_z/part-00011-fbeb69b5-031b-429f-94b4-065f1375a831.c000.snappy.parquet', name='part-00011-fbeb69b5-031b-429f-94b4-065f1375a831.c000.snappy.parquet', size=526754, modificationTime=1790128297000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta_z/part-00012-705cdd56-7443-4aba-9019-74800d65e598.c000.snappy.parquet', name='part-00012-705cdd56-7443-4aba-9019-74800d65e598.c000.snappy.parquet', size=526958, modificationTime=1790243040000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta_z/part-00012-d47be7b7-b31b-4720-93fe-56f2f5d67493.c000.snappy.parquet', name='part-00012-d47be7b7-b31b-4720-93fe-56f2f5d67493.c000.snappy.parquet', size=526958, modificationTime=1790128297000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta_z/part-00013-5cd24a87-a38c-4670-ac3d-a6506c6c1bd1.c000.snappy.parquet', name='part-00013-5cd24a87-a38c-4670-ac3d-a6506c6c1bd1.c000.snappy.parquet', size=527002, modificationTime=1790128297000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta_z/part-00013-dd011fd8-a084-4210-9dbe-75185ee0119c.c000.snappy.parquet', name='part-00013-dd011fd8-a084-4210-9dbe-75185ee0119c.c000.snappy.parquet', size=527002, modificationTime=1790243040000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta_z/part-00014-b95d6084-813d-43c3-b9ab-3e3f3a895c18.c000.snappy.parquet', name='part-00014-b95d6084-813d-43c3-b9ab-3e3f3a895c18.c000.snappy.parquet', size=526557, modificationTime=1790243040000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta_z/part-00014-e17a3b32-eb81-4546-93c7-65c86aed67fe.c000.snappy.parquet', name='part-00014-e17a3b32-eb81-4546-93c7-65c86aed67fe.c000.snappy.parquet', size=526557, modificationTime=1790128297000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta_z/part-00015-83b184fe-e3ed-4372-9e69-007d73cd9404.c000.snappy.parquet', name='part-00015-83b184fe-e3ed-4372-9e69-007d73cd9404.c000.snappy.parquet', size=525858, modificationTime=1790243040000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta_z/part-00015-eb9c8662-6702-41fd-8f63-17da0a89f687.c000.snappy.parquet', name='part-00015-eb9c8662-6702-41fd-8f63-17da0a89f687.c000.snappy.parquet', size=525858, modificationTime=1790128297000),
 FileInfo(path='/Volumes/workspace/default/data/output/sales_delta_z/_delta_log/', name='', size=None, modificationTime=None)]

In [5]:
display(spark.sql("SELECT * FROM workspace.default.sales_delta_z"))

DataFrame[InvoiceNo: string, StockCode: string, Description: string, Quantity: int, InvoiceDate: string, UnitPrice: double, CustomerID: int, Country: string]

In [6]:
display(spark.sql("SELECT * FROM workspace.default.sales_delta_z WHERE InvoiceNo = '540646'"))

DataFrame[InvoiceNo: string, StockCode: string, Description: string, Quantity: int, InvoiceDate: string, UnitPrice: double, CustomerID: int, Country: string]

In [7]:
display(spark.sql("SELECT MIN(InvoiceNo) AS MIN_INVOICE_NO, MAX(InvoiceNo) AS MAX_INVOICE_NO, _metadata.file_name FROM workspace.default.sales_delta_z GROUP BY _metadata.file_name ORDER BY MIN_INVOICE_NO"))

DataFrame[MIN_INVOICE_NO: string, MAX_INVOICE_NO: string, file_name: string]

In [12]:
# spark.conf.set("spark.databricks.delta.optimize.maxFileSize", 64*1024*8) this won't work so try the following
spark.sql("""
  ALTER TABLE workspace.default.sales_delta_z
  SET TBLPROPERTIES ('delta.targetFileSize' = '64mb')
""")

spark.sql("OPTIMIZE workspace.default.sales_delta_z ZORDER BY (InvoiceNo)")

DataFrame[path: string, metrics: struct<numFilesAdded:bigint,numFilesRemoved:bigint,filesAdded:struct<min:bigint,max:bigint,avg:double,totalFiles:bigint,totalSize:bigint>,filesRemoved:struct<min:bigint,max:bigint,avg:double,totalFiles:bigint,totalSize:bigint>,partitionsOptimized:bigint,zOrderStats:struct<strategyName:string,inputCubeFiles:struct<num:bigint,size:bigint>,inputOtherFiles:struct<num:bigint,size:bigint>,inputNumCubes:bigint,mergedFiles:struct<num:bigint,size:bigint>,numOutputCubes:bigint,mergedNumCubes:bigint>,clusteringStats:struct<inputZCubeFiles:struct<numFiles:bigint,size:bigint>,inputOtherFiles:struct<numFiles:bigint,size:bigint>,inputNumZCubes:bigint,mergedFiles:struct<numFiles:bigint,size:bigint>,numOutputZCubes:bigint>,numBins:bigint,numBatches:bigint,totalConsideredFiles:bigint,totalFilesSkipped:bigint,preserveInsertionOrder:boolean,numFilesSkippedToReduceWriteAmplification:bigint,numBytesSkippedToReduceWriteAmplification:bigint,startTimeMs:bigint,endTimeMs:bigint,totalClusterParallelism:bigint,totalScheduledTasks:bigint,autoCompactParallelismStats:struct<maxClusterActiveParallelism:bigint,minClusterActiveParallelism:bigint,maxSessionActiveParallelism:bigint,minSessionActiveParallelism:bigint>,deletionVectorStats:struct<numDeletionVectorsRemoved:bigint,numDeletionVectorRowsRemoved:bigint>,recompressionCodec:string,numTableColumns:bigint,numTableColumnsWithStats:bigint,totalTaskExecutionTimeMs:bigint,skippedArchivedFiles:bigint,clusteringMetrics:struct<sizeOfTableInBytesBeforeLazyClustering:bigint,isNewMetadataCreated:boolean,isPOTriggered:boolean,isFull:boolean,approxClusteringQuality:double,approxClusteringQualityPerColumn:array<double>,approxClusteringCoverage:double,compactionType:string,numFilesSkippedWithoutStats:bigint,numFilesClassifiedToIntermediateNodes:bigint,sizeOfFilesClassifiedToIntermediateNodesInBytes:bigint,logicalSizeOfFilesClassifiedToIntermediateNodesInBytes:bigint,numFilesClassifiedToLeafNodes:bigint,sizeOfFilesClassifiedToLeafNodesInBytes:bigint,logicalSizeOfFilesClassifiedToLeafNodesInBytes:bigint,numThreadsForClassifier:int,clusterThresholdStrategy:string,minFileSize:bigint,maxFileSize:bigint,nodeMinNumFilesToCompact:bigint,numNullValuesEncounteredForTransforms:bigint,numIdealFiles:bigint,numIdealFilesWithTrimmedStringMaxValue:bigint,numAddedFilesWithSameMinMaxOnClusteringColumns:array<bigint>,numClusteringTasksPlanned:int,numClusteringTasksNotPlannedDueToPO:int,totalSizeOfDataToClusterInBytesNotPlannedDueToPO:bigint,numCompactionTasksPlanned:int,numCompactionTasksPlannedUndoneDueToPO:int,numOptimizeBatchesPlanned:int,numLeafNodesExpanded:bigint,numLeafNodesClustered:bigint,numGetFilesForNodeCalls:bigint,numSamplingJobs:bigint,numLeafNodesCompacted:bigint,numLeafNodesCompactedUndoneDueToPO:bigint,numIntermediateNodesCompacted:bigint,numIntermediateNodesCompactedUndoneDueToPO:bigint,totalSizeOfDataToCompactInBytes:bigint,totalSizeOfDataToCompactInBytesUndoneDueToPO:bigint,totalLogicalSizeOfDataToCompactInBytes:bigint,totalLogicalSizeOfDataToCompactInBytesUndoneDueToPO:bigint,numIntermediateNodesClustered:bigint,numFilesSkippedAfterExpansion:bigint,numSmallFilesSkippedAfterExpansion:bigint,totalSizeOfFilesSkippedAfterExpansionInBytes:bigint,totalSizeOfSmallFilesSkippedAfterExpansionInBytes:bigint,totalLogicalSizeOfFilesSkippedAfterExpansionInBytes:bigint,totalLogicalSizeOfSmallFilesSkippedAfterExpansionInBytes:bigint,totalSizeOfDataToRewriteInBytes:bigint,totalLogicalSizeOfDataToRewriteInBytes:bigint,timeMetrics:struct<classifierTimeMs:bigint,optimizerTimeMs:bigint,metadataLoadTimeMs:bigint,totalGetFilesForNodeCallsTimeMs:bigint,totalSamplingTimeMs:bigint,metadataCreationTimeMs:bigint>,maxOptimizeBatchesInParallel:bigint,currentIteration:int,maxIterations:int,clusteringStrategy:string,splitStrategy:string,numDowncastDimensions:int,withPredicates:boolean,numFilesSkippedByPredicates:bigint,predicates:array<string>,isPipelinedOptimizer:boolean,pipelinedTotalPlanningTimeMs:bigint,pipelinedTotalBatchWaitTimeMs:bigint,pipelinedPostFirstBatchWaitTimeMs:bigint,coordinatorEventMetrics:struct<numPermitsGranted:bigint,numPermitsDenied:bigint,numCapacityGatedRequests:bigint,peakBufferedTaskBytes:bigint,peakInFlightPlanningBytes:bigint,totalEventsProcessed:bigint,numEventLogBatchesFlushed:int,totalGetFilesPermitWaitTimeMs:bigint,totalCreateTaskPermitWaitTimeMs:bigint,totalGetFilesTimeMs:bigint,totalCreateTaskTimeMs:bigint,permitTimeoutFired:boolean,permitTimeoutFiredAtMs:bigint>,pipelinedOptimizerStatus:string,pipelinedAssemblerMetrics:struct<numBatchesEmitted:int,numLargeTaskBatches:int,minTasksPerBatch:int,maxTasksPerBatch:int,totalTasksInBatches:int,minBatchBytes:bigint,maxBatchBytes:bigint>,compressionRatioFromSampling:double,compressionRatioSource:string,compressionRatioNumSamples:bigint,compressionRatioSamplingTimeMs:bigint,compressionRatioTriggeredScaling:boolean,compressionRatioFromPersistedEntry:boolean,compressionRatioChosen:double,compressionRatioStalenessReason:string>,fileAgeHistogram:struct<sortedBinBoundaries:array<bigint>,fileCounts:array<bigint>,totalBytes:array<bigint>>,numFilesSortedWithinFiles:bigint>]

In [ ]:
display(spark.sql("SELECT MIN(InvoiceNo) AS MIN_INVOICE_NO, MAX(InvoiceNo) AS MAX_INVOICE_NO, _metadata.file_name FROM workspace.default.sales_delta_z GROUP BY _metadata.file_name ORDER BY MIN(InvoiceNo)"))

DataFrame[MIN_INVOICE_NO: string, MAX_INVOICE_NO: string, file_name: string]

In [14]:
display(spark.sql("SELECT * FROM workspace.default.sales_delta_z WHERE InvoiceNo = '540646'"))

DataFrame[InvoiceNo: string, StockCode: string, Description: string, Quantity: int, InvoiceDate: string, UnitPrice: double, CustomerID: int, Country: string]

In [15]:
spark.sql("OPTIMIZE workspace.default.sales_delta_z ZORDER BY (Country, InvoiceNo)")

DataFrame[path: string, metrics: struct<numFilesAdded:bigint,numFilesRemoved:bigint,filesAdded:struct<min:bigint,max:bigint,avg:double,totalFiles:bigint,totalSize:bigint>,filesRemoved:struct<min:bigint,max:bigint,avg:double,totalFiles:bigint,totalSize:bigint>,partitionsOptimized:bigint,zOrderStats:struct<strategyName:string,inputCubeFiles:struct<num:bigint,size:bigint>,inputOtherFiles:struct<num:bigint,size:bigint>,inputNumCubes:bigint,mergedFiles:struct<num:bigint,size:bigint>,numOutputCubes:bigint,mergedNumCubes:bigint>,clusteringStats:struct<inputZCubeFiles:struct<numFiles:bigint,size:bigint>,inputOtherFiles:struct<numFiles:bigint,size:bigint>,inputNumZCubes:bigint,mergedFiles:struct<numFiles:bigint,size:bigint>,numOutputZCubes:bigint>,numBins:bigint,numBatches:bigint,totalConsideredFiles:bigint,totalFilesSkipped:bigint,preserveInsertionOrder:boolean,numFilesSkippedToReduceWriteAmplification:bigint,numBytesSkippedToReduceWriteAmplification:bigint,startTimeMs:bigint,endTimeMs:bigint,totalClusterParallelism:bigint,totalScheduledTasks:bigint,autoCompactParallelismStats:struct<maxClusterActiveParallelism:bigint,minClusterActiveParallelism:bigint,maxSessionActiveParallelism:bigint,minSessionActiveParallelism:bigint>,deletionVectorStats:struct<numDeletionVectorsRemoved:bigint,numDeletionVectorRowsRemoved:bigint>,recompressionCodec:string,numTableColumns:bigint,numTableColumnsWithStats:bigint,totalTaskExecutionTimeMs:bigint,skippedArchivedFiles:bigint,clusteringMetrics:struct<sizeOfTableInBytesBeforeLazyClustering:bigint,isNewMetadataCreated:boolean,isPOTriggered:boolean,isFull:boolean,approxClusteringQuality:double,approxClusteringQualityPerColumn:array<double>,approxClusteringCoverage:double,compactionType:string,numFilesSkippedWithoutStats:bigint,numFilesClassifiedToIntermediateNodes:bigint,sizeOfFilesClassifiedToIntermediateNodesInBytes:bigint,logicalSizeOfFilesClassifiedToIntermediateNodesInBytes:bigint,numFilesClassifiedToLeafNodes:bigint,sizeOfFilesClassifiedToLeafNodesInBytes:bigint,logicalSizeOfFilesClassifiedToLeafNodesInBytes:bigint,numThreadsForClassifier:int,clusterThresholdStrategy:string,minFileSize:bigint,maxFileSize:bigint,nodeMinNumFilesToCompact:bigint,numNullValuesEncounteredForTransforms:bigint,numIdealFiles:bigint,numIdealFilesWithTrimmedStringMaxValue:bigint,numAddedFilesWithSameMinMaxOnClusteringColumns:array<bigint>,numClusteringTasksPlanned:int,numClusteringTasksNotPlannedDueToPO:int,totalSizeOfDataToClusterInBytesNotPlannedDueToPO:bigint,numCompactionTasksPlanned:int,numCompactionTasksPlannedUndoneDueToPO:int,numOptimizeBatchesPlanned:int,numLeafNodesExpanded:bigint,numLeafNodesClustered:bigint,numGetFilesForNodeCalls:bigint,numSamplingJobs:bigint,numLeafNodesCompacted:bigint,numLeafNodesCompactedUndoneDueToPO:bigint,numIntermediateNodesCompacted:bigint,numIntermediateNodesCompactedUndoneDueToPO:bigint,totalSizeOfDataToCompactInBytes:bigint,totalSizeOfDataToCompactInBytesUndoneDueToPO:bigint,totalLogicalSizeOfDataToCompactInBytes:bigint,totalLogicalSizeOfDataToCompactInBytesUndoneDueToPO:bigint,numIntermediateNodesClustered:bigint,numFilesSkippedAfterExpansion:bigint,numSmallFilesSkippedAfterExpansion:bigint,totalSizeOfFilesSkippedAfterExpansionInBytes:bigint,totalSizeOfSmallFilesSkippedAfterExpansionInBytes:bigint,totalLogicalSizeOfFilesSkippedAfterExpansionInBytes:bigint,totalLogicalSizeOfSmallFilesSkippedAfterExpansionInBytes:bigint,totalSizeOfDataToRewriteInBytes:bigint,totalLogicalSizeOfDataToRewriteInBytes:bigint,timeMetrics:struct<classifierTimeMs:bigint,optimizerTimeMs:bigint,metadataLoadTimeMs:bigint,totalGetFilesForNodeCallsTimeMs:bigint,totalSamplingTimeMs:bigint,metadataCreationTimeMs:bigint>,maxOptimizeBatchesInParallel:bigint,currentIteration:int,maxIterations:int,clusteringStrategy:string,splitStrategy:string,numDowncastDimensions:int,withPredicates:boolean,numFilesSkippedByPredicates:bigint,predicates:array<string>,isPipelinedOptimizer:boolean,pipelinedTotalPlanningTimeMs:bigint,pipelinedTotalBatchWaitTimeMs:bigint,pipelinedPostFirstBatchWaitTimeMs:bigint,coordinatorEventMetrics:struct<numPermitsGranted:bigint,numPermitsDenied:bigint,numCapacityGatedRequests:bigint,peakBufferedTaskBytes:bigint,peakInFlightPlanningBytes:bigint,totalEventsProcessed:bigint,numEventLogBatchesFlushed:int,totalGetFilesPermitWaitTimeMs:bigint,totalCreateTaskPermitWaitTimeMs:bigint,totalGetFilesTimeMs:bigint,totalCreateTaskTimeMs:bigint,permitTimeoutFired:boolean,permitTimeoutFiredAtMs:bigint>,pipelinedOptimizerStatus:string,pipelinedAssemblerMetrics:struct<numBatchesEmitted:int,numLargeTaskBatches:int,minTasksPerBatch:int,maxTasksPerBatch:int,totalTasksInBatches:int,minBatchBytes:bigint,maxBatchBytes:bigint>,compressionRatioFromSampling:double,compressionRatioSource:string,compressionRatioNumSamples:bigint,compressionRatioSamplingTimeMs:bigint,compressionRatioTriggeredScaling:boolean,compressionRatioFromPersistedEntry:boolean,compressionRatioChosen:double,compressionRatioStalenessReason:string>,fileAgeHistogram:struct<sortedBinBoundaries:array<bigint>,fileCounts:array<bigint>,totalBytes:array<bigint>>,numFilesSortedWithinFiles:bigint>]

In [17]:
display(spark.sql("SELECT COUNTRY, MIN(InvoiceNo) AS MIN_INVOICE_NO, MAX(InvoiceNo) AS MAX_INVOICE_NO, _metadata.file_name FROM workspace.default.sales_delta_z GROUP BY COUNTRY, _metadata.file_name ORDER BY COUNTRY, MIN(InvoiceNo)"))

DataFrame[COUNTRY: string, MIN_INVOICE_NO: string, MAX_INVOICE_NO: string, file_name: string]

In [18]:
display(spark.sql("SELECT * FROM workspace.default.sales_delta_z WHERE InvoiceNo = '536389' AND Country = 'Australia'"))

DataFrame[InvoiceNo: string, StockCode: string, Description: string, Quantity: int, InvoiceDate: string, UnitPrice: double, CustomerID: int, Country: string]

## Delta Tables - Deletion Vectors and Liquid Clustering | Optimize Delta Tables | Delta Clustering

In [24]:
# Read csv data from location "dbfs:/Volumes/samples/databricks/datasets/online_retail/data-001/data.csv"
display(spark.sql("SELECT * FROM read_files('dbfs:/Volumes/samples/databricks/datasets/online_retail/data-001/data.csv', header => true, format => 'csv')"))

DataFrame[InvoiceNo: string, StockCode: string, Description: string, Quantity: int, InvoiceDate: string, UnitPrice: double, CustomerID: int, Country: string, _rescued_data: string]

In [25]:
spark.sql("CREATE TABLE workspace.default.online_retail_sales AS SELECT * FROM read_files('dbfs:/Volumes/samples/databricks/datasets/online_retail/data-001/data.csv', header => true, format => 'csv')")

DataFrame[num_affected_rows: bigint, num_inserted_rows: bigint]

In [26]:
display(spark.sql("SELECT * FROM workspace.default.online_retail_sales"))

DataFrame[InvoiceNo: string, StockCode: string, Description: string, Quantity: int, InvoiceDate: string, UnitPrice: double, CustomerID: int, Country: string, _rescued_data: string]

In [27]:
display(spark.sql("DESCRIBE EXTENDED workspace.default.online_retail_sales"))

DataFrame[col_name: string, data_type: string, comment: string]

In [30]:
# Delete deletionvector
spark.sql("ALTER TABLE workspace.default.online_retail_sales SET TBLPROPERTIES ('delta.enableDeletionVectors' = 'false')")

DataFrame[]

In [31]:
# Delete data without deletion vectors with InvoiceNo = '536365'
spark.sql("DELETE FROM workspace.default.online_retail_sales WHERE InvoiceNo = '536365'")

DataFrame[num_affected_rows: bigint]

In [33]:
display(spark.sql("DESCRIBE HISTORY workspace.default.online_retail_sales"))

DataFrame[version: bigint, timestamp: timestamp, userId: string, userName: string, operation: string, operationParameters: map<string,string>, job: struct<jobId:string,jobName:string,jobRunId:string,runId:string,jobOwnerId:string,triggerType:string,workspaceId:string>, notebook: struct<notebookId:string>, queryHistoryStatementId: string, clusterId: string, readVersion: bigint, isolationLevel: string, isBlindAppend: boolean, operationMetrics: map<string,string>, userMetadata: string, engineInfo: string]

In [34]:
# Enable deletion vectors
spark.sql("ALTER TABLE workspace.default.online_retail_sales SET TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')")

DataFrame[]

In [35]:
# Delete data with deletionvector with InvoiceNo = '536367'
spark.sql("DELETE FROM workspace.default.online_retail_sales WHERE InvoiceNo = '536367'")

DataFrame[num_affected_rows: bigint]

In [36]:
display(spark.sql("DESCRIBE HISTORY workspace.default.online_retail_sales"))

DataFrame[version: bigint, timestamp: timestamp, userId: string, userName: string, operation: string, operationParameters: map<string,string>, job: struct<jobId:string,jobName:string,jobRunId:string,runId:string,jobOwnerId:string,triggerType:string,workspaceId:string>, notebook: struct<notebookId:string>, queryHistoryStatementId: string, clusterId: string, readVersion: bigint, isolationLevel: string, isBlindAppend: boolean, operationMetrics: map<string,string>, userMetadata: string, engineInfo: string]

In [ ]:
# spark.sql("OPTIMIZE workspace.default.online_retail_sales")

In [37]:
# Liquid Clustering
spark.sql("ALTER TABLE workspace.default.online_retail_sales CLUSTER BY (InvoiceNo)")

DataFrame[]

In [38]:
display(spark.sql("DESCRIBE HISTORY workspace.default.online_retail_sales"))

DataFrame[version: bigint, timestamp: timestamp, userId: string, userName: string, operation: string, operationParameters: map<string,string>, job: struct<jobId:string,jobName:string,jobRunId:string,runId:string,jobOwnerId:string,triggerType:string,workspaceId:string>, notebook: struct<notebookId:string>, queryHistoryStatementId: string, clusterId: string, readVersion: bigint, isolationLevel: string, isBlindAppend: boolean, operationMetrics: map<string,string>, userMetadata: string, engineInfo: string]

In [ ]:
# To remove liquid clustering
# spark.sql("ALTER TABLE workspace.default.online_retail_sales CLUSTER BY NONE")
# At the time of creation of table too we can give the CLUSTER BY clause to enable liquid clustering.